"""added profile pic

Revision ID: d60fa7e4f8fe
Revises: 88e369e3bd6a
Create Date: 2022-09-14 15:38:41.980879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd60fa7e4f8fe'
down_revision = '88e369e3bd6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author')
    op.add_column('users', sa.Column('about_author', sa.Text(length=500), nullable=True))
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'about_author')
    op.add_column('posts', sa.Column('author', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
